apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-petclinic-deployment
  labels:
    app: petclinic
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:

    kind: Deployment
    name: {{ .Release.Name }}-petclinic-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50


  ---
apiVersion: apps/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-petclinic-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-petclinic-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
